"""create hardware specification tables

Revision ID: d660406e9b74
Revises: b76f5d7aecbc
Create Date: 2026-08-29 13:28:39.569040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd660406e9b74'
down_revision: Union[str, Sequence[str], None] = 'b76f5d7aecbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('supported_motherboard_form_factors', sa.JSON(), nullable=False),
    sa.Column('max_gpu_length_mm', sa.Integer(), nullable=False),
    sa.Column('max_cpu_cooler_height_mm', sa.Integer(), nullable=False),
    sa.Column('psu_form_factor', sa.String(length=50), nullable=False),
    sa.Column('drive_bays', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_specifications_id'), 'case_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_case_specifications_product_id'), 'case_specifications', ['product_id'], unique=True)
    op.create_table('cooling_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cooler_type', sa.String(length=50), nullable=False),
    sa.Column('supported_sockets', sa.JSON(), nullable=False),
    sa.Column('radiator_size_mm', sa.Integer(), nullable=True),
    sa.Column('fan_size_mm', sa.Integer(), nullable=True),
    sa.Column('max_tdp_watts', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooling_specifications_id'), 'cooling_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_cooling_specifications_product_id'), 'cooling_specifications', ['product_id'], unique=True)
    op.create_table('cpu_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('socket', sa.String(length=50), nullable=False),
    sa.Column('core_count', sa.Integer(), nullable=False),
    sa.Column('thread_count', sa.Integer(), nullable=False),
    sa.Column('base_clock_ghz', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('boost_clock_ghz', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('tdp_watts', sa.Integer(), nullable=False),
    sa.Column('architecture', sa.String(length=100), nullable=True),
    sa.Column('integrated_graphics', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpu_specifications_id'), 'cpu_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_cpu_specifications_product_id'), 'cpu_specifications', ['product_id'], unique=True)
    op.create_table('gpu_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('chipset', sa.String(length=100), nullable=False),
    sa.Column('vram_gb', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('core_clock_mhz', sa.Integer(), nullable=True),
    sa.Column('boost_clock_mhz', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=False),
    sa.Column('tdp_watts', sa.Integer(), nullable=False),
    sa.Column('recommended_psu_watts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_specifications_id'), 'gpu_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_gpu_specifications_product_id'), 'gpu_specifications', ['product_id'], unique=True)
    op.create_table('memory_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=False),
    sa.Column('speed_mhz', sa.Integer(), nullable=False),
    sa.Column('module_count', sa.Integer(), nullable=False),
    sa.Column('cas_latency', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_specifications_id'), 'memory_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_memory_specifications_product_id'), 'memory_specifications', ['product_id'], unique=True)
    op.create_table('motherboard_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('socket', sa.String(length=50), nullable=False),
    sa.Column('chipset', sa.String(length=50), nullable=False),
    sa.Column('form_factor', sa.String(length=50), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('memory_slots', sa.Integer(), nullable=False),
    sa.Column('max_memory_gb', sa.Integer(), nullable=False),
    sa.Column('pcie_version', sa.String(length=50), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motherboard_specifications_id'), 'motherboard_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_motherboard_specifications_product_id'), 'motherboard_specifications', ['product_id'], unique=True)
    op.create_table('psu_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('wattage', sa.Integer(), nullable=False),
    sa.Column('efficiency_rating', sa.String(length=50), nullable=False),
    sa.Column('modularity', sa.String(length=50), nullable=False),
    sa.Column('form_factor', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psu_specifications_id'), 'psu_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_psu_specifications_product_id'), 'psu_specifications', ['product_id'], unique=True)
    op.create_table('storage_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(length=50), nullable=False),
    sa.Column('form_factor', sa.String(length=50), nullable=False),
    sa.Column('read_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('write_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_specifications_id'), 'storage_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_storage_specifications_product_id'), 'storage_specifications', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_specifications_product_id'), table_name='storage_specifications')
    op.drop_index(op.f('ix_storage_specifications_id'), table_name='storage_specifications')
    op.drop_table('storage_specifications')
    op.drop_index(op.f('ix_psu_specifications_product_id'), table_name='psu_specifications')
    op.drop_index(op.f('ix_psu_specifications_id'), table_name='psu_specifications')
    op.drop_table('psu_specifications')
    op.drop_index(op.f('ix_motherboard_specifications_product_id'), table_name='motherboard_specifications')
    op.drop_index(op.f('ix_motherboard_specifications_id'), table_name='motherboard_specifications')
    op.drop_table('motherboard_specifications')
    op.drop_index(op.f('ix_memory_specifications_product_id'), table_name='memory_specifications')
    op.drop_index(op.f('ix_memory_specifications_id'), table_name='memory_specifications')
    op.drop_table('memory_specifications')
    op.drop_index(op.f('ix_gpu_specifications_product_id'), table_name='gpu_specifications')
    op.drop_index(op.f('ix_gpu_specifications_id'), table_name='gpu_specifications')
    op.drop_table('gpu_specifications')
    op.drop_index(op.f('ix_cpu_specifications_product_id'), table_name='cpu_specifications')
    op.drop_index(op.f('ix_cpu_specifications_id'), table_name='cpu_specifications')
    op.drop_table('cpu_specifications')
    op.drop_index(op.f('ix_cooling_specifications_product_id'), table_name='cooling_specifications')
    op.drop_index(op.f('ix_cooling_specifications_id'), table_name='cooling_specifications')
    op.drop_table('cooling_specifications')
    op.drop_index(op.f('ix_case_specifications_product_id'), table_name='case_specifications')
    op.drop_index(op.f('ix_case_specifications_id'), table_name='case_specifications')
    op.drop_table('case_specifications')
    # ### end Alembic commands ###
